# Generated by Django 4.1 on 2022-08-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authatication', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone_Number',
        ),
    ]
